Faculty/Controllers/CoursesController.cs
using Microsoft.AspNetCore.Mvc;
using Faculty.WEB.ViewModel;
using Faculty.BLL.DTO;
using System.Collections.Generic;
using Faculty.BLL.Interfaces;

namespace Faculty.WEB.Controllers
{
    public class CoursesController : Controller
    {
        private const int AllCourses = 0;
        private readonly IFacultyServices<CourseDTO> _coursesServices;
        private readonly IFacultyServices<GroupDTO> _groupsServices;

        public CoursesController(IFacultyServices<CourseDTO> coursesServices,
                                 IFacultyServices<GroupDTO> groupsServices)
        {
            _coursesServices = coursesServices;
            _groupsServices = groupsServices;
        }

        public IActionResult Index()
        {
            var model = CreateModel(AllCourses);

            return View(model);
        }

        public IActionResult ChooseCourse(int courseId)
        {
            var model = CreateModel(courseId);

            return View(model);
        }

        public FullListViewModel CreateModel(int courseId)
        {
            FullListViewModel model = new();

            if (courseId != 0)
            {
                model.Courses = new List<CourseDTO> { _coursesServices.GetById(courseId) };
                model.Groups = _groupsServices.GetByKeyId(courseId);
            }
            else
            {
                model.Courses = _coursesServices.GetAll();
                model.Groups = _groupsServices.GetAll();
            }

            return model;
        }
    }
}

Faculty/Controllers/GroupsController.cs
using Microsoft.AspNetCore.Mvc;
using Faculty.BLL.Interfaces;
using Faculty.WEB.ViewModel;
using Faculty.BLL.DTO;
using System.Collections.Generic;

namespace Faculty.WEB.Controllers
{
    public class GroupsController : Controller
    {
        private const int AllGroups = 0;
        private readonly IFacultyServices<GroupDTO> _groupsServices;
        private readonly IFacultyServices<StudentDTO> _studentsServices;

        public GroupsController(IFacultyServices<GroupDTO> groupsServices,
                                IFacultyServices<StudentDTO> studentsServices)
        {
            _groupsServices = groupsServices;
            _studentsServices = studentsServices;
        }

        public IActionResult Index()
        {
            var model = CreateModel(AllGroups);

            return View(model);
        }

        public IActionResult ChooseGroup(int groupId)
        {
            var model = CreateModel(groupId);

            return View(model);
        }

        public IActionResult EditGroup(int groupId)
        {
            if (groupId != 0)
            {
                var model = CreateModel(groupId);
                return View(model);
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }

        public IActionResult SaveGroup(GroupDTO model)
        {
            _groupsServices.Save(model);
            return RedirectToAction("Index", "Home");
        }

        public IActionResult DeleteGroup(int groupId)
        {
            if (_groupsServices.GetById(groupId) != null)
            {
                ViewBag.DeleteGroup = "There are students in this group. I can't delete this group.";
            }
            else
            {
                ViewBag.DeleteGroup = "There are no students in this group. I can delete this group.";
            }
            return View();
        }

        public FullListViewModel CreateModel(int groupId)
        {
            FullListViewModel model = new();

            if (groupId != 0)
            {
                model.Groups = new List<GroupDTO> { _groupsServices.GetById(groupId) };
                model.Students = _studentsServices.GetByKeyId(groupId);
            }
            else
            {
                model.Groups = _groupsServices.GetAll();
                model.Students = _studentsServices.GetAll();
            }

            return model;
        }
    }
}

Faculty/Controllers/StudentsController.cs
using Microsoft.AspNetCore.Mvc;
using Faculty.BLL.Interfaces;
using Faculty.WEB.ViewModel;
using Faculty.BLL.DTO;
using System.Collections.Generic;

namespace Faculty.WEB.Controllers
{
    public class StudentsController : Controller
    {
        private const int AllStudents = 0;

        private readonly IFacultyServices<StudentDTO> _studentsServices;
         

        public StudentsController(IFacultyServices<StudentDTO> studentsServices)
        {
            _studentsServices = studentsServices;
        }

        public IActionResult Index()
        {
            var model = CreateModel(AllStudents);

            return View(model);
        }

        public IActionResult EditStudent(int studentId)
        {
            if (studentId != 0)
            {
                var model = CreateModel(studentId);
                return View(model);
            }
            return RedirectToAction("Index", "Home");
        }

        public IActionResult SaveStudent(StudentDTO student)
        {
            _studentsServices.Save(student);
            return RedirectToAction("Index", "Home");
        }

        public FullListViewModel CreateModel(int studentId)
        {
            FullListViewModel model = new();

            if (studentId != 0)
            {
                model.Students = new List<StudentDTO> { _studentsServices.GetById(studentId) };
            }
            else
            {
                model.Students = _studentsServices.GetAll();
            }

            return model;
        }
    }
}

Faculty/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Faculty</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <!--                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WEB</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                -->                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Courses" asp-action="Index">Courses</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Groups" asp-action="Index">Groups</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Students" asp-action="Index">Students</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
</body>
</html>